# Generated by Django 4.2.5 on 2023-10-15 13:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anagrafica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ragione', models.TextField(verbose_name='Ragione sociale')),
                ('attivita', models.TextField(verbose_name='Tipo attività svolta')),
                ('indirizzo', models.TextField(verbose_name='Indirizzo:')),
                ('civico', models.TextField(verbose_name='Civico:')),
                ('comune', models.TextField(verbose_name='Comune:')),
                ('provincia', models.TextField(verbose_name='Provincia:')),
                ('cap', models.TextField(verbose_name='CAP:')),
                ('email', models.TextField(verbose_name='Email:')),
                ('codice_fiscale', models.TextField(verbose_name='Codice Fiscale:')),
                ('regime_fiscale', models.TextField(verbose_name='Regime Fiscale:')),
                ('codice_palestra', models.TextField(verbose_name='Codice Palestra Registrazione:')),
                ('referente', models.TextField(verbose_name='Referente')),
                ('abbveviativo', models.TextField(verbose_name='Abbreviativo contratto')),
                ('nome_app', models.TextField(verbose_name='Nome sull applicativo')),
            ],
        ),
    ]
