# Generated by Django 4.2.5 on 2023-10-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagrafica',
            name='telefono_cellulare',
            field=models.TextField(blank=True, null=True, verbose_name='Telefono Cellulare:'),
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='telefono_fisso',
            field=models.TextField(blank=True, null=True, verbose_name='Telefono Fisso:'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='abbveviativo',
            field=models.TextField(blank=True, null=True, verbose_name='Abbreviativo contratto'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='attivita',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo attività svolta'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='cap',
            field=models.TextField(blank=True, null=True, verbose_name='CAP:'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='civico',
            field=models.TextField(blank=True, null=True, verbose_name='Civico:'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='codice_fiscale',
            field=models.TextField(blank=True, null=True, verbose_name='Codice Fiscale:'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='codice_palestra',
            field=models.TextField(blank=True, null=True, verbose_name='Codice Palestra Registrazione:'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='comune',
            field=models.TextField(blank=True, null=True, verbose_name='Comune:'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='indirizzo',
            field=models.TextField(blank=True, null=True, verbose_name='Indirizzo:'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='nome_app',
            field=models.TextField(blank=True, null=True, verbose_name='Nome sull applicativo'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='provincia',
            field=models.TextField(blank=True, null=True, verbose_name='Provincia:'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='ragione',
            field=models.TextField(blank=True, null=True, verbose_name='Ragione sociale'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='referente',
            field=models.TextField(blank=True, null=True, verbose_name='Referente'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='regime_fiscale',
            field=models.TextField(blank=True, null=True, verbose_name='Regime Fiscale:'),
        ),
    ]
