# Generated by Django 4.2.5 on 2023-10-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_anagrafica_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(help_text='Nome corso ( max 23 caratteri )', max_length=23, verbose_name='Nome corso ( max 23 caratteri )')),
                ('descrizione', models.TextField(blank=True, help_text='Inserisci una rapida descrizione dell attività svolta durante il corso. Non usare testi troppo lunghi, consigliamo massimo 50 parole', null=True, verbose_name='Nome corso ( max 23 caratteri )')),
                ('costo_base', models.TextField(help_text='1', verbose_name='Costo base del corso:')),
                ('tipologia_lezione', models.CharField(choices=[('G', 'Gruppo'), ('P', 'Private')], max_length=1, verbose_name='Tipologia Lezione:')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Data si crea in automatico', verbose_name='Data creazione del corso')),
            ],
            options={
                'verbose_name': 'Corso',
                'verbose_name_plural': 'Corsi',
                'ordering': ('-pub_date',),
            },
        ),
    ]
