# Generated by Django 4.2.5 on 2023-10-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_alter_anagrafica_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome', models.TextField(help_text='Cognome', verbose_name='Cognome')),
                ('nome', models.TextField(help_text='Nome', verbose_name='Nome')),
                ('ragione', models.TextField(blank=True, null=True, verbose_name='Ragione sociale')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Data inserimento', verbose_name='Data inserimento')),
                ('indirizzo', models.TextField(blank=True, null=True, verbose_name='Indirizzo:')),
                ('civico', models.TextField(blank=True, null=True, verbose_name='Civico:')),
                ('comune', models.TextField(blank=True, null=True, verbose_name='Comune:')),
                ('provincia', models.TextField(blank=True, null=True, verbose_name='Provincia:')),
                ('cap', models.TextField(blank=True, null=True, verbose_name='CAP:')),
                ('email', models.TextField(blank=True, null=True, verbose_name='Email:')),
                ('telefono_fisso', models.TextField(blank=True, null=True, verbose_name='Telefono Fisso:')),
                ('telefono_cellulare', models.TextField(blank=True, null=True, verbose_name='Telefono Cellulare:')),
                ('codice_fiscale', models.TextField(blank=True, null=True, verbose_name='Codice Fiscale:')),
                ('partita_iva', models.TextField(blank=True, null=True, verbose_name='Partita Iva:')),
            ],
            options={
                'verbose_name': 'Istruttore',
                'verbose_name_plural': 'Istruttori',
                'ordering': ('-pub_date',),
            },
        ),
    ]
