# Generated by Django 4.2.5 on 2023-10-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_listino', models.TextField(help_text='Nome listino', verbose_name='Nome listino')),
                ('qta_crediti', models.TextField(help_text='Quantità Crediti', verbose_name='Quantità Crediti')),
                ('validita', models.TextField(blank=True, help_text='Validitá', null=True, verbose_name='Validitá')),
                ('validita_giorni', models.TextField(help_text='Validitá in giorni', verbose_name='Validitá in giorni')),
                ('prezzo_finale', models.TextField(blank=True, null=True, verbose_name='Prezzo finale')),
                ('tasse', models.TextField(blank=True, null=True, verbose_name='Tasse')),
                ('imponibile', models.TextField(blank=True, null=True, verbose_name='Imponibile')),
                ('prezzi_open', models.TextField(blank=True, null=True, verbose_name='Listino prezzi OPEN')),
                ('pagamento_online', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2, verbose_name='Pagamento Online')),
                ('tipo_vendita', models.CharField(choices=[('Acquisto signolo', 'Acquisto signolo'), ('Abbonamento mensile', 'Abbonamento mensile')], max_length=20, verbose_name='Tipo Vendita')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Data inserimento', verbose_name='Data inserimento')),
            ],
            options={
                'verbose_name': 'Listino Prezzi',
                'verbose_name_plural': 'Listino Prezzi',
                'ordering': ('-pub_date',),
            },
        ),
    ]
