# Generated by Django 4.2.5 on 2023-10-20 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0009_pricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagrafica',
            name='author',
            field=models.ForeignKey(help_text='Автор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anagrafica', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='author',
            field=models.ForeignKey(help_text='Автор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='author',
            field=models.ForeignKey(help_text='Автор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricelists', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='author',
            field=models.ForeignKey(help_text='Автор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
