# Generated by Django 4.2.5 on 2023-10-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_anagrafica_author_lesson_author_pricelist_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='costo_base',
            field=models.CharField(help_text='1', max_length=100, verbose_name='Costo base del corso:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='descrizione',
            field=models.TextField(blank=True, help_text='Inserisci una rapida descrizione massimo 50 parole', null=True, verbose_name='Descrizione'),
        ),
    ]
